// <auto-generated />
using Group6_WSAD_FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group6_WSAD_FinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201004519_AddBlakeSeed")]
    partial class AddBlakeSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Group6_WSAD_FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Music",
                            DifficultyLevel = 1,
                            Name = "Attending Concerts",
                            OwnerId = 1,
                            Reason = "I love attending concerts because live music feels completely different and more personal than listening at home. Over the past five years, I’ve gone to dozens of shows with friends, ranging from indie and pop concerts to full EDM festivals. I’ve seen artists like Conan Gray, Kesha, The Weeknd, COIN, The Lumineers, The Band Camino, The Driver Era, Mt. Joy, and multiple Breakaway Festivals. Concerts are one of my favorite ways to spend time because the energy, the atmosphere, and the shared experience with the crowd make every show unforgettable. I try to stay within budget and not spend more than $100 per concert, but I still prioritize going whenever I can. I already have festivals lined up for next year, and the concert I want to go to the most is Billie Eilish because she is my dream upcoming artist to see live."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Video Games",
                            DifficultyLevel = 1,
                            Name = "Gaming",
                            OwnerId = 2,
                            Reason = "Gaming is one of my favorite passtimes and I enjoy both playing alone and with friends. Genres I enjoy most include Survival, Simulation, Action/Adventure, Sports, and FPS. Some of my favorite games to play include Ark: Survival Evolved/Ascended, Elite Dangerous, RocketLeague, Deep Rock Galactic, Battlefield 6, and Rust. I have been playing video games since I was very young and started out on the PlayStation 1. One of the first games I remember playing was the original Gran Turismo and Crash Bandicoot. One of the physically oldest games I have extensively played is Toejam and Earl on the Sega Genesis. Since then, I have owned Playstation 2, 3, and 4, the Xbox 360, One, and Series X, the Nintendo DS, 3DS, WII, and Switch Lite, the Oculus Quest 1 and 2, and more recently I built a Gaming PC. Across all those systems I've likely owned or played hundreds of games and logged tens of thousands of hours playing them. "
                        });
                });

            modelBuilder.Entity("Group6_WSAD_FinalProject.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bella"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Blake"
                        });
                });

            modelBuilder.Entity("Group6_WSAD_FinalProject.Models.Hobby", b =>
                {
                    b.HasOne("Group6_WSAD_FinalProject.Models.Owner", "Owner")
                        .WithMany("Hobbies")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Group6_WSAD_FinalProject.Models.Owner", b =>
                {
                    b.Navigation("Hobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
